<h1>403 Proibido</h1>
<p>
    <?php if ($error == 'error-unauthorized-controller') : ?>
        Você não está autorizado a acessar <?php echo($controller);?>
        <?php if ($action) : ?>
        ::<?php echo($action);?>Action()
        <?php endif;?>
        .
    <?php elseif ($error == 'error-unauthorized-route') : ?>
        Você não está autorizado a acessar <?php echo $route;?>.
    <?php else : ?>
    Ocorreu um erro desconhecido.
    <?php endif;?>
</p>
