<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php if($this->zfcUserIdentity() !== false){ ?>
 <?php if($this->isAllowed('admin') === true){ ?>

 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

 <?php } ?>
 <?php } ?>



 <table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>

            <?php if($this->zfcUserIdentity() !== false){ ?>
            <?php if($this->isAllowed('admin') === true){ ?>
            <td>
                <a href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                <a href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            </td>
            <?php } ?>
            <?php } ?>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
