<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Hellow World</a>

        <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/album">Album</a></li>


            </ul>
            <div class="pull-right">
	            <?php if($this->zfcUserIdentity() !== false){ ?>
	            <?php if($this->isAllowed('admin') === true){ ?>
	            	<ul class="nav">
		                <li class="dropdown">
		                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
		                    <ul class="dropdown-menu">
		                        <li><a href="/admin">Página do Admin</a></li>
		                        <li><a href="/user/change-email">Alterar E-mail</a></li>
                            <li><a href="/user/change-password">Alterar Senha</a></li>
		                    </ul>
		                </li>
		            </ul>
	            <?php } else { ?>
	            	<ul class="nav">
		                <li class="dropdown">
		                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configurações<b class="caret"></b></a>
		                    <ul class="dropdown-menu">
		                        <li><a href="/user/change-password">Alterar Senha</a></li>
		                        <li><a href="/user/change-email">Alterar E-mail</a></li>
		                    </ul>
		                </li>
		            </ul>
	            <?php } ?>

	                <a class="btn" href="/user/logout">Logout</a>
	            <?php } else { ?>
	            	<a class="btn" href="/user/login">Login</a>
	            	<a class="btn" href="/user/register">Registrar</a>
	            <?php } ?>
            </div>

        </div>
    </div>
</div>
